# Generated by Django 4.0.4 on 2022-07-21 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_user'),
        ('favorite', '0004_alter_favorite_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_prod', to='product.product'),
        ),
    ]
