# Generated by Django 4.0.4 on 2022-07-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='getter',
        ),
    ]
