# Generated by Django 4.0.4 on 2022-07-22 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_rename_receiver_message_getter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='getter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='getter', to=settings.AUTH_USER_MODEL),
        ),
    ]
